# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x9e\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"H\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\r\n\x05index\x18\x04 \x01(\x05\"H\n\x0f\x44\x42UpdateRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ommit_index\x18\x03 \x01(\x05\"P\n\x10\x44\x42UpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rapplied_index\x18\x02 \x01(\x05\x12\x14\n\x0c\x61pplied_data\x18\x03 \x01(\x0c\")\n\x11\x46indLeaderRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\t\"C\n\x12\x46indLeaderResponse\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x32\x91\x02\n\x0bRaftService\x12\x36\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\"\x00\x12J\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\"\x00\x12;\n\x08\x44\x42Update\x12\x15.raft.DBUpdateRequest\x1a\x16.raft.DBUpdateResponse\"\x00\x12\x41\n\nFindLeader\x12\x17.raft.FindLeaderRequest\x1a\x18.raft.FindLeaderResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTEREQUEST._serialized_start=20
  _VOTEREQUEST._serialized_end=116
  _VOTERESPONSE._serialized_start=118
  _VOTERESPONSE._serialized_end=168
  _APPENDENTRIESREQUEST._serialized_start=171
  _APPENDENTRIESREQUEST._serialized_end=329
  _APPENDENTRIESRESPONSE._serialized_start=331
  _APPENDENTRIESRESPONSE._serialized_end=385
  _LOGENTRY._serialized_start=387
  _LOGENTRY._serialized_end=459
  _DBUPDATEREQUEST._serialized_start=461
  _DBUPDATEREQUEST._serialized_end=533
  _DBUPDATERESPONSE._serialized_start=535
  _DBUPDATERESPONSE._serialized_end=615
  _FINDLEADERREQUEST._serialized_start=617
  _FINDLEADERREQUEST._serialized_end=658
  _FINDLEADERRESPONSE._serialized_start=660
  _FINDLEADERRESPONSE._serialized_end=727
  _RAFTSERVICE._serialized_start=730
  _RAFTSERVICE._serialized_end=1003
# @@protoc_insertion_point(module_scope)
