# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import itinerary_pb2 as itinerary__pb2


class ItineraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItinerary = channel.unary_unary(
                '/itinerary.ItineraryService/GetItinerary',
                request_serializer=itinerary__pb2.Empty.SerializeToString,
                response_deserializer=itinerary__pb2.ItineraryList.FromString,
                )
        self.UpdateItinerary = channel.unary_unary(
                '/itinerary.ItineraryService/UpdateItinerary',
                request_serializer=itinerary__pb2.UpdateRequest.SerializeToString,
                response_deserializer=itinerary__pb2.UpdateResponse.FromString,
                )
        self.StreamItineraryChanges = channel.unary_stream(
                '/itinerary.ItineraryService/StreamItineraryChanges',
                request_serializer=itinerary__pb2.Empty.SerializeToString,
                response_deserializer=itinerary__pb2.ItineraryList.FromString,
                )
        self.ReplicateItinerary = channel.unary_unary(
                '/itinerary.ItineraryService/ReplicateItinerary',
                request_serializer=itinerary__pb2.UpdateRequest.SerializeToString,
                response_deserializer=itinerary__pb2.Empty.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/itinerary.ItineraryService/Heartbeat',
                request_serializer=itinerary__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=itinerary__pb2.HeartbeatResponse.FromString,
                )


class ItineraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItinerary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItinerary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamItineraryChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateItinerary(self, request, context):
        """Replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeats and leader detection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItineraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItinerary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItinerary,
                    request_deserializer=itinerary__pb2.Empty.FromString,
                    response_serializer=itinerary__pb2.ItineraryList.SerializeToString,
            ),
            'UpdateItinerary': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItinerary,
                    request_deserializer=itinerary__pb2.UpdateRequest.FromString,
                    response_serializer=itinerary__pb2.UpdateResponse.SerializeToString,
            ),
            'StreamItineraryChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamItineraryChanges,
                    request_deserializer=itinerary__pb2.Empty.FromString,
                    response_serializer=itinerary__pb2.ItineraryList.SerializeToString,
            ),
            'ReplicateItinerary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateItinerary,
                    request_deserializer=itinerary__pb2.UpdateRequest.FromString,
                    response_serializer=itinerary__pb2.Empty.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=itinerary__pb2.HeartbeatRequest.FromString,
                    response_serializer=itinerary__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'itinerary.ItineraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItineraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItinerary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itinerary.ItineraryService/GetItinerary',
            itinerary__pb2.Empty.SerializeToString,
            itinerary__pb2.ItineraryList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItinerary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itinerary.ItineraryService/UpdateItinerary',
            itinerary__pb2.UpdateRequest.SerializeToString,
            itinerary__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamItineraryChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/itinerary.ItineraryService/StreamItineraryChanges',
            itinerary__pb2.Empty.SerializeToString,
            itinerary__pb2.ItineraryList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateItinerary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itinerary.ItineraryService/ReplicateItinerary',
            itinerary__pb2.UpdateRequest.SerializeToString,
            itinerary__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itinerary.ItineraryService/Heartbeat',
            itinerary__pb2.HeartbeatRequest.SerializeToString,
            itinerary__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
