# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itinerary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fitinerary.proto\x12\titinerary\"9\n\rItineraryItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\x05\"8\n\rItineraryList\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.itinerary.ItineraryItem\">\n\rUpdateRequest\x12\x14\n\x0citinerary_id\x18\x01 \x01(\x05\x12\x17\n\x0fquantity_change\x18\x02 \x01(\x05\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\".\n\x10HeartbeatRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"&\n\x11HeartbeatResponse\x12\x11\n\tis_leader\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xe8\x02\n\x10ItineraryService\x12:\n\x0cGetItinerary\x12\x10.itinerary.Empty\x1a\x18.itinerary.ItineraryList\x12\x46\n\x0fUpdateItinerary\x12\x18.itinerary.UpdateRequest\x1a\x19.itinerary.UpdateResponse\x12\x46\n\x16StreamItineraryChanges\x12\x10.itinerary.Empty\x1a\x18.itinerary.ItineraryList0\x01\x12@\n\x12ReplicateItinerary\x12\x18.itinerary.UpdateRequest\x1a\x10.itinerary.Empty\x12\x46\n\tHeartbeat\x12\x1b.itinerary.HeartbeatRequest\x1a\x1c.itinerary.HeartbeatResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itinerary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITINERARYITEM._serialized_start=30
  _ITINERARYITEM._serialized_end=87
  _ITINERARYLIST._serialized_start=89
  _ITINERARYLIST._serialized_end=145
  _UPDATEREQUEST._serialized_start=147
  _UPDATEREQUEST._serialized_end=209
  _UPDATERESPONSE._serialized_start=211
  _UPDATERESPONSE._serialized_end=244
  _HEARTBEATREQUEST._serialized_start=246
  _HEARTBEATREQUEST._serialized_end=292
  _HEARTBEATRESPONSE._serialized_start=294
  _HEARTBEATRESPONSE._serialized_end=332
  _EMPTY._serialized_start=334
  _EMPTY._serialized_end=341
  _ITINERARYSERVICE._serialized_start=344
  _ITINERARYSERVICE._serialized_end=704
# @@protoc_insertion_point(module_scope)
