# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_cart_pb2 as user__cart__pb2


class UserCartServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/usercart.UserCartService/Login',
                request_serializer=user__cart__pb2.LoginRequest.SerializeToString,
                response_deserializer=user__cart__pb2.LoginResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/usercart.UserCartService/CreateAccount',
                request_serializer=user__cart__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=user__cart__pb2.CreateAccountResponse.FromString,
                )
        self.AddToCart = channel.unary_unary(
                '/usercart.UserCartService/AddToCart',
                request_serializer=user__cart__pb2.UpdateCartRequest.SerializeToString,
                response_deserializer=user__cart__pb2.CartResponse.FromString,
                )
        self.RemoveFromCart = channel.unary_unary(
                '/usercart.UserCartService/RemoveFromCart',
                request_serializer=user__cart__pb2.UpdateCartRequest.SerializeToString,
                response_deserializer=user__cart__pb2.CartResponse.FromString,
                )
        self.GetCart = channel.unary_unary(
                '/usercart.UserCartService/GetCart',
                request_serializer=user__cart__pb2.UserRequest.SerializeToString,
                response_deserializer=user__cart__pb2.CartResponse.FromString,
                )
        self.Checkout = channel.unary_unary(
                '/usercart.UserCartService/Checkout',
                request_serializer=user__cart__pb2.UserRequest.SerializeToString,
                response_deserializer=user__cart__pb2.CheckoutResponse.FromString,
                )
        self.ReplicateCart = channel.unary_unary(
                '/usercart.UserCartService/ReplicateCart',
                request_serializer=user__cart__pb2.ReplicateCartRequest.SerializeToString,
                response_deserializer=user__cart__pb2.Empty.FromString,
                )
        self.ReplicateUser = channel.unary_unary(
                '/usercart.UserCartService/ReplicateUser',
                request_serializer=user__cart__pb2.ReplicateUserRequest.SerializeToString,
                response_deserializer=user__cart__pb2.Empty.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/usercart.UserCartService/Heartbeat',
                request_serializer=user__cart__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=user__cart__pb2.HeartbeatResponse.FromString,
                )


class UserCartServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateCart(self, request, context):
        """Replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeats and leader detection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserCartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=user__cart__pb2.LoginRequest.FromString,
                    response_serializer=user__cart__pb2.LoginResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=user__cart__pb2.CreateAccountRequest.FromString,
                    response_serializer=user__cart__pb2.CreateAccountResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=user__cart__pb2.UpdateCartRequest.FromString,
                    response_serializer=user__cart__pb2.CartResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=user__cart__pb2.UpdateCartRequest.FromString,
                    response_serializer=user__cart__pb2.CartResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=user__cart__pb2.UserRequest.FromString,
                    response_serializer=user__cart__pb2.CartResponse.SerializeToString,
            ),
            'Checkout': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkout,
                    request_deserializer=user__cart__pb2.UserRequest.FromString,
                    response_serializer=user__cart__pb2.CheckoutResponse.SerializeToString,
            ),
            'ReplicateCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateCart,
                    request_deserializer=user__cart__pb2.ReplicateCartRequest.FromString,
                    response_serializer=user__cart__pb2.Empty.SerializeToString,
            ),
            'ReplicateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateUser,
                    request_deserializer=user__cart__pb2.ReplicateUserRequest.FromString,
                    response_serializer=user__cart__pb2.Empty.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=user__cart__pb2.HeartbeatRequest.FromString,
                    response_serializer=user__cart__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usercart.UserCartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserCartService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/Login',
            user__cart__pb2.LoginRequest.SerializeToString,
            user__cart__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/CreateAccount',
            user__cart__pb2.CreateAccountRequest.SerializeToString,
            user__cart__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/AddToCart',
            user__cart__pb2.UpdateCartRequest.SerializeToString,
            user__cart__pb2.CartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/RemoveFromCart',
            user__cart__pb2.UpdateCartRequest.SerializeToString,
            user__cart__pb2.CartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/GetCart',
            user__cart__pb2.UserRequest.SerializeToString,
            user__cart__pb2.CartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Checkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/Checkout',
            user__cart__pb2.UserRequest.SerializeToString,
            user__cart__pb2.CheckoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/ReplicateCart',
            user__cart__pb2.ReplicateCartRequest.SerializeToString,
            user__cart__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/ReplicateUser',
            user__cart__pb2.ReplicateUserRequest.SerializeToString,
            user__cart__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usercart.UserCartService/Heartbeat',
            user__cart__pb2.HeartbeatRequest.SerializeToString,
            user__cart__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
